version: '3.1'

services:
  db:
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3308:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=cf-tool
    volumes: 
      - ./storage:/var/lib/mysql
      
  api:
    build: .
    ports:
      - 5000:5000